name: UPDATE_APP_ACTION

on:
  push:
    branches:
      - main
jobs:
  update-readme-with-appinfo:
    runs-on: ubuntu-latest

    steps:
        env:
          APPSETTINGS: ${{secrets.APPSETTINGS}}
          DATABASE_NAME: ${{secrets.DATABASE_NAME}}